# Generated by Django 5.2.8 on 2025-11-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, help_text='Enter discount percentage (e.g. 20 for 20%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_options',
            field=models.CharField(default='500G,1KG,2KG', help_text='Comma-separated weight options such as 500G,1KG,2KG,500ML,1L', max_length=200),
        ),
    ]
